"""Weekly statistics endpoint.

GET /api/stats/weekly?session_id=<uuid> -> combined CO2 figure for the
current week for the specified anonymous browser session, plus a breakdown.

The ``session_id`` query parameter is an opaque UUID generated by the browser
on first visit (stored in localStorage). It is not a credential and requires
no backend authentication -- it is only used as a Firestore query filter so
each browser sees its own weekly totals rather than the global sum.
"""

import logging

from fastapi import APIRouter, HTTPException, Query, status

from services import firestore_client

logger = logging.getLogger(__name__)
router = APIRouter()


@router.get("/api/stats/weekly")
def weekly_stats(
    session_id: str = Query(default="", max_length=64),
) -> dict:
    """Return this week's CO2 total and breakdown for the requesting browser session."""
    try:
        return firestore_client.weekly_totals(session_id=session_id)
    except Exception as exc:  # noqa: BLE001 - never leak internals
        logger.error("Weekly aggregation failed: %s", exc)
        raise HTTPException(
            status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Could not load weekly stats right now.",
        )
